[project]
name = "algo-predictions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pykalshi[dataframe]>=0.3.6",
    "python-dotenv>=1.2.1",
]
